
[window]
opacity = 0.7
decorations = "none"

[font]
normal = { family = "Cica", style = "Regular" }
bold = { family = "Cica", style = "Bold" }
italic = { family = "Cica", style = "Italic" }
bold_italic = { family = "Cica", style = "Bold Italic" }
size = 14

[colors]
vi_mode_cursor = { text = "#2e3440", cursor = "#d8dee9"}
[selection]
save_to_clipboard = true

[terminal]
osc52 = "OnlyCopy"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij attach --index 0 --create"]

[keyboard]
bindings = [
{ key = "t", mods = "Alt", action = "CreateNewWindow" } 
, { key = "+", mods = "Control", action = "IncreaseFontSize" } 
, { key = "-", mods = "Control", action = "DecreaseFontSize" } 
, { key = "0", mods = "Control", action = "ResetFontSize" } 
, { key = "q", mods = "Control", action = "Quit" } 
, { key = "s", mods = "Alt", action = "SpawnNewInstance" } 
, { key = "v", mods = "Alt", action = "ToggleViMode" } 
, { key = "m", mods = "Alt", action = "ToggleMaximized" } 
]
