# Beets configuration --------------------------------------------------------
# beets version 1.4.7
# Python version 3.7.0
# Matthew Rothfuss 10/03/2018

library: ~/.config/beets/musiclibrary.blb
directory: /mnt/hdd1/My Music/

replace:
    '[\\/]': '-'
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': ''
    '\s+$': ''
    '^\s+': ''
    '^-': '-'

art_filename: folder
threaded: yes
format_item: $artist - $album - $title
sort_item: artist+ year+ album+ disc+ track+
sort_album: albumartist+ year+ album+
per_disc_numbering: no
clutter:
  - "Thumbs.DB"
  - "Thumbs.db"
  - "thumbs.db"
  - ".DS_Store"
  - "folder.*"
  - "*.m3u"
asciify_paths: no
id3v23: yes
va_name : 'Various Artists'

import:
  write: no
  move: no
  copy: no
  resume: ask
  timid: no
  log: beetslog.log
  incremental: no
  from_scratch: yes
  quiet: yes
  quiet_fallback: yes
  default_action: skip
  languages: jp en kr
  autotag: no
  ignore:
    - ".*"
    - "System Volume Information"
    - "lost+found"
  duplicate_action: remove
    #  set_fields:
    #    genre: 'No Write Tag'
    #    artist: 'No Write Tag'
    #    album: 'No Write Tag'

# Paths ----------------------------------------------------------------------
paths:
  default: $albumartist/$album%aunique{}/${filetrack}_${title}
  singleton: Singletons/$artist - $title
  comp: Various Artists/$album%aunique{}/${filetrack}_${title}
  albumtype:soundtrack: Original Soundtrack/$album/${filetrack}_${title}

# Plugins --------------------------------------------------------------------

plugins: info inline duplicates rewrite edit embedart fetchart scrub zero play

edit:
  itemfields: album albumartist artist year disc disctotal genre genres title track tracktotal

embedart:
  auto: no
  ifempty: yes
  maxwidth: 0
  quality: 0
  remove_art_file: no

scrub:
  auto: yes

zero:
  fields: comments original_year comp bpm year month day disc disctotal
  year: [^0$]
  disc: [^0$]
  disctotal: [^0$]
  update_database: true

play:
  #command: /usr/bin/mpv --no-video
  command: /usr/bin/mpv --autofit=50%

fetchart:
  sources: filesystem coverart itunes amazon albumart
  cover_format: JPEG

item_fields:
  filetrack: u'%02i' % (track) if tracktotal > 9 else u'%01i' % (track)
